LIGHT_THEME = {
    "bg_app": "#f4f7fb",
    "bg_panel": "#eef3f9",
    "bg_surface": "#ffffff",
    "bg_surface_alt": "#f8fbff",
    "bg_hover": "#f1f6fd",
    "bg_selected": "#e6f0ff",
    "text_main": "#0f172a",
    "text_body": "#1e293b",
    "text_muted": "#64748b",
    "text_soft": "#94a3b8",
    "border": "#dbe4f0",
    "border_strong": "#c7d4e5",
    "primary": "#1d4ed8",
    "primary_hover": "#1e40af",
    "primary_soft": "#dbeafe",
    "success": "#15803d",
    "success_soft": "#dcfce7",
    "warning": "#b45309",
    "warning_soft": "#fff7ed",
    "danger": "#dc2626",
    "danger_soft": "#fef2f2",
    "info": "#2563eb",
    "info_soft": "#eff6ff",
    "shadow": "rgba(15, 23, 42, 0.08)",
}
